### ISSUE TITLE
BUG: Enabling more then two channels is not possible

### ISSUE THREAD

**Issue by schote** [schote/spectrum-console#30]
- When more than two channels are enabled in the device configuration, the read number of enabled channels from card equals zero 
- Happens directly after channel enable: `sp.spcm_dwSetParam_i32(self.card, sp.SPC_CHENABLE, channel_selection)`
- Enabling channel 0 and/or channel 1 works, even independently

### Resolution attempts
- Tried to replaced `channel_selection` by `sp.CHANNEL0 | sp.CHANNEL1 | sp.CHANNEL2` and observed the same behavior
- Tried to set the channel amplitude to `10000` according to the other channels

**Comment by hiddendb** [comment]
The only valid number of active channels is 2^n. Activating 4 channels is working without a problem.

**Comment by schote** [comment]
> The only valid number of active channels is 2^n. Activating 4 channels is working without a problem.

Thanks for figuring out! 
Did you also try 8 channels?
Do you remember the section in the manual? We should reference it somewhere in the code.

**Comment by hiddendb** [comment]
- 8 channels is working as well. Can get a noise signal out of all of them.
- Reference in manual is p. 72 [https://spectrum-instrumentation.com/dl/m2p_59xx_manual_english.pdf]
- `device_config.yaml`should be a good place
