### ISSUE TITLE
BUG: Missing Gate Windows?

### ISSUE THREAD

**Issue by schote** [schote/spectrum-console#40]
The implementation of readout to numpy array was successful and improved the readout performance.
However, since that update it happens in irregular intervals, that some of the receive data is missing.
The propblem tend to appear, when the console logging mode is set not higher than warning.
It seems like every 2nd readout/gate is missed. 
E.g. an averaged spectrum (10 times average) then leads to only 5 averages in total.

It is not clear, how to trigger this behavior exactly.

**Comment by berksilemek** [comment]
With the new numpy implementation, reading probably was faster than or simultaneous with the receiver buffer. Without waiting for DMA to be finished to read data by numpy pointers was creating this problem. Now, this issue was fixed by moving wait DMA to beginning of the reading.
